<?php

// Reserved column names
return array(
                'id' => 'Coupon ID | Coupon ID',
                'post_title' => 'Coupon Title | Name of the coupon ',
                //'post_name' => 'Coupon Permalink | Unique part of the coupon URL',
                'post_status' => 'Coupon Status | Coupon Status ( published , draft ...)',
                //'post_content' => 'Coupon Description | Description about the Coupon',
                'post_excerpt' => 'Coupon Short Description | Short description about the Coupon',
                'post_date' => 'Post Date | Coupon posted date',
                'discount_type' => 'Coupon Type | fixed_cart OR percent OR fixed_product OR percent_product',
                'coupon_amount' => 'Coupon Amount | Numeric values',
                'individual_use' => 'Individual Use? | yes or no',
                'product_ids' => 'Assocoated Product Ids | With comma(,) Separator' ,
                'exclude_product_ids' => 'Exclude Product Ids | With comma(,) Separator',
                'usage_count' => 'No of times used | Numeric Values',
                'usage_limit' => 'Usage Limit Per Coupon | Numeric Values',
                'usage_limit_per_user' => 'Usage Limit Per User | Numeric Values',
                'limit_usage_to_x_items' => 'Limit Usage To X Items | Maximum Number Of Individual Items This Coupon Can Apply',
                'expiry_date' => 'Expiry Date | YYYY-MM-DD',
                'free_shipping' => 'Is Free Shipping? | yes or no',
                'exclude_sale_items' => 'Is Exclude Sale Items? | yes or no',
                'product_categories' => 'Product Categories | with comma(,) Separator',
                'exclude_product_categories' => 'Exclude Product  Categories | With comma(,) Separator',
                'minimum_amount' => 'Minimum Amount | Numeric',
                'maximum_amount' => 'Maximum Amount | Numeric',
                'customer_email' => 'Restricted Customers Email Ids| With comma(,) Separator',
                //'post_date_gmt' => 'Post Date GMT | Tooltip data Status',
                /*'sku' => 'Product SKU | Product SKU - This will unique and Product identifier',
                'post_parent' => 'Parent ID | Prent Product ID , if you are importing variation Product',
                'parent_sku' => 'Parent SKU | Prent Product SKU , if you are importing variation Product',
                'post_password' => 'Post Password | To Protect a post with password',
                'post_author' => 'Prodcut Author | Prodcut Author ( 1 - Admin )',
                'menu_order' => 'Menu Order | If menu enabled , menu order',
                'comment_status' => 'Comment Status | Comment Status ( Open or Closed comments for this prodcut)',
                'downloadable' => 'Type: Downloadable | Is Product is downloadable eg:- Book',
                'virtual' => 'Type: Virtual | Is Product is virtual',
                'visibility' => 'Visibility: Visibility | Visibility status ( hidden or visible)',
                'featured' => 'Visibility: Featured | Featured Product',
                'stock' => 'Inventory: Stock | Stock quantity',
                'stock_status' => 'Inventory: Stock Status | InStock or OutofStock',
                'backorders' => 'Inventory: Backorders | Backorders',
                'manage_stock' => 'Inventory: Manage Stock | yes to enable no to disable',
                'sale_price' => 'Price: Sale Price | Sale Price ',
                'regular_price' => 'Price: Regular Price | Regular Price',
                'sale_price_dates_from' => 'Sale Price Dates: From | Sale Price Dates effect from',
                'sale_price_dates_to' => 'Sale Price Dates: To | Sale Price Dates effect to',
                'weight' => 'Dimensions: Weight | Wight of product in LB , OZ , KG as of your woocommerce Unit',
                'length' => 'Dimensions: length | Length',
                'width' => 'Dimensions: width | Width',
                'height' => 'Dimensions: height | Height',
                'tax_status' => 'Tax: Tax Status | Taxable product or not',
                'tax_class' => 'Tax: Tax Class | Tax class ( eg:- reduced rate)',
                'upsell_ids' => 'Related Products: Upsell IDs | Upsell Product ids',
                'crosssell_ids' => 'Related Products: Crosssell IDs | Crosssell Product ids',
                'file_paths' => 'Downloads: File Paths (WC 2.0.x) | File Paths',
                'downloadable_files' => 'Downloads: Downloadable Files (WC 2.1.x) | Downloadable Files',
                'download_limit' => 'Downloads: Download Limit | Download Limit',
                'download_expiry' => 'Downloads: Download Expiry | Download Expiry ',
                'product_url' => 'External: Product URL | Product URL if the Product is external',
                'button_text' => 'External: Button Text | Buy button text for Product , if the Product is external',
                'images' => 'Images/Gallery | Image URLs seperated with &#124;',
                'meta:total_sales' => 'meta:total_sales | Total sales for the Product',
                'tax:product_type' => 'Product Type | ( eg:- simple , variable)',
                'tax:product_cat' =>  'Product Categories | Product related categories',
                'tax:product_tag' => 'Product Tags | Product related tags',
                'tax:product_shipping_class' => 'Product Shipping Class | Allow you to group similar products for shipping',
                // YOAST
                '_yoast_wpseo_focuskw' => 'meta:_yoast_wpseo_focuskw | yoast SEO',
                '_yoast_wpseo_title' => 'meta:_yoast_wpseo_title | yoast SEO',
                '_yoast_wpseo_metadesc' => 'meta:_yoast_wpseo_metadesc | yoast SEO',
                '_yoast_wpseo_metakeywords' => 'meta:_yoast_wpseo_metakeywords | yoast SEO',*/

    
);