<?php 

// Reserved column names
return array(
	'id',
	'discount_type',
	'post_id',
	'post_title',
	'post_name',
    'post_status',
    'post_date',
	'post_date_gmt',
    //'post_content',
	'post_excerpt',
	//'post_parent',
	//'post_password',
	//'sku',
    'post_type',
	'post_author',
	//'menu_order',
	'postmeta',
	//'comment_status',
	//'downloadable',
	//'virtual',
	//'visibility',
	//'stock',
	//'stock_status',
	//'backorders',
	//'manage_stock',
	//'price',
	//'sale_price',
	//'regular_price',
	//'weight',
	// 'length',
	// 'width',
	// 'height',
	// 'tax_status',
	// 'tax_class',
	// 'upsell_ids',
	// 'crosssell_ids',
	// 'upsell_skus',
	// 'crosssell_skus',
	// 'sale_price_dates_from',
	// 'sale_price_dates_to',
	// 'min_variation_price',
	// 'max_variation_price',
	// 'min_variation_regular_price',
	// 'max_variation_regular_price',
	// 'min_variation_sale_price',
	// 'max_variation_sale_price',
	// 'featured',
	// 'file_path',
	// 'file_paths',
	// 'downloadable_files',
	// 'download_limit',
	// 'download_expiry',
	// 'product_url',
	// 'button_text',
	// 'default_attributes'
	'coupon_amount',
	'individual_use',
	'product_ids',
	'exclude_product_ids',
        'usage_count',
	'usage_limit',
	'usage_limit_per_user',
	'limit_usage_to_x_items',
	'expiry_date',
	'free_shipping',
	'exclude_sale_items',
	'product_categories',
	'exclude_product_categories',
	'minimum_amount',
	'maximum_amount',
	'customer_email',

);